[package]
name = "custom-loop-fanctl"
version = "0.1.0"
authors = ["Derek Witt <derek@witt.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
panic-halt = "0.2.0"
usbd-serial = "0.1.1"
usb-device = "0.2.7"


[dependencies.itsybitsy_m0]
version = "0.10.0"
features = ["usb"]